services:
  web:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    develop:
      watch:
        - path: web/package.json
          action: rebuild
        - path: web/
          target: /app
          action: sync
