apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: web
build:
  artifacts:
    - image: skaffold-buildpacks-node
      context: .
      docker:
        dockerfile: ./deploy/Dockerfile
      sync: 
        manual:  
          - src: web/
            dest: /app
manifests:
  rawYaml:
    - deploy/kubernetes.yaml
